---
title: "Analyse de données CSVR 19-20 - Série AN"
Author: "Nicolas Bressoud"
date: "octobre 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
source("csvr2020_an_script.R")
```

# Contexte
La saisie de données se déroule dans le cadre de la formation-recherche-action au CSVR, durant l'année scolaire 2019-2020.

4 classes sont impliquées dans la présent série.

Le design proposait un système de liste d'attente (2x2 classes). On renonce à traiter les données pour vérifier l'utilisation du programme. Celui-ci n'a pas été monitoré. En effet, on ne sait pas qui a fait les forces de quelle manière et à quel moment.

Voici un état des données brutes avant nettoyage :
Première série (n=91) : entre le 21 octobre 2019 et le 4 novembre 2019
Deuxième série (n=14) : entre le 17 et le 19 décembre 2019
Troisième série (n=33) : entre le 20 et le 23 janvier 2020
Quatrième série (n=17) : entre le 19 mars et le 2 avril 2020

# Principes du nettoyage
Dans la perspective de la recherche corrélationnelle, nous nettoyons les données en gardant toutes les observations qui obéissent aux règles suivantes :
- ID vraisemblable
- entrée complète

Les analyse devront prendre en compte les données aux ID identiques (variation sur le temps).

# Mesures
Les données mesurent :
- l'engagement scolaire (SEM) : 17 items en 3 sous-dimensions (comportemental, affectif, cognitif) <!-- Calculer les sous-dimensions -->
- le bien-être (Kidscreen adapté) : 18 items en 4 sous-dimensions (bien-être physique 4/5 , bien-être psychologique 3/6, pairs et support social 4/4, env. scolaire 4/4, bullying 3 items) <!-- vérifier les noms corrects des dimensions du kidscreen -->
- confiance en soi : 10 items
- questions courtes (RS): 3 items pour 3 dimensions (énergie, amis, bien-être)

## No. des items à inverser 
- SEM : 5 et 10 (échelle à 5)
- Kidscreen : 6, 15, 16, 17 (échelle à 5)
- confiance en soi : 4, 5, 6, 7, 9 (échelle à 9)

